### ISSUE TITLE
リポジトリ整理のためのブランチマージ

### ISSUE THREAD

**Issue by NishaMe** [2017pro02/Ishibetsu#16]
「homeブランチをdevelopとmainブランチへ移動させる」

現在の問題：
リポジトリを移した際、宙ぶらりんのブランチが発生してしまった。
宙ぶらりんのブランチを手動でmain,developへマージしなくてはならない。

やることリスト（上から順番にチェックボックスにチェック入れてください）
- [ ]   1.sentakuで葛西さんがプルリクを出す
- [ ]   2.葛西さんはプルリクの番号をここへコメントで残す
　　　  →コメントへの残し方（https://qiita.com/jollyjoester/items/a59c03d9d1cf9d0a3365）
- [ ]  3.遼と上杉がコードのチェックをして、コメントをここに残す（良くても悪くても残して）
- [ ]  4.葛西さんがブランチをマージ

- [ ]  5.マージできたhomeのブランチを手動でdevelopへマージ
　　　 →ここの作業は、主に遼、上杉、葛西それぞれの箇所でバグがないか確認しながらマージして欲しい
　     6.完全に終わったらissueを閉じる

**Comment by JumpingBird** [comment]
現状では１から４を自分一人でやった状態でした…
