### ISSUE TITLE
ホーム画面のメニューバー作成

### ISSUE THREAD

**Issue by daleksprinter** [2017pro02/Ishibetsu#4]
方針
絞り込みボタンが押されたらページ最上部に移動
到達したらslidedownでメニューを表示

問題
移動中に絞り込みボタンを押したら最上部に移動したあとスクロールイベントの続きが発生するので想定外の移動が発生する

**Comment by JumpingBird** [comment]
setting.htmlの絞り込みボタンの部分をhome.htmlに書き直している

**Comment by NishaMe** [comment]
誰が担当してる？
Assigneesから担当者アサインして

**Comment by JumpingBird** [comment]
ボタン素材ください

**Comment by JumpingBird** [comment]
スライドバーは完了しました
あとはボタンに変更するだけです

**Comment by JumpingBird** [comment]
iOSではスクロール時に上へ移動しようとすると不具合が出ますが、Androidでは自然に動きます
But iOSではスクロールできないように指定できますが、Androidではスクロール止めれません
